= Esercitazione su JDBC
Cristian Lucchesi <cristian.lucchesi@gmail.com>
2016-02-19
:source-highlighter: highlightjs
:backend: revealjs
:revealjs_theme: night
:revealjs_slideNumber: true

== Preparazione ambiente di sviluppo

Strumenti utilizzati nell'esercitazione:

 * Java 8 -> http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
 * Editor Eclipse -> http://www.eclipse.org
 * Maven -> https://maven.apache.org
 * Database h2 -> http://www.h2database.com/

Gli strumenti sono disponibili nelle penne USB.

== Esercitazione su Java e JDBC

Creazione di una applicazione *anagrafica*.

Passi principali:
[%step]
* Creazione di un progetto Java + Maven
* Connessione al Database
* Creazione della tabella
* Definizione di un Data Access Object (DAO)
* Lettura dalla tabella
* Interfaccia command line per la gestione dei dati
* Metodi di inserimento/modifica/creazione

== Creazione del progetto

[%step]
* in Eclipse -> file -> New -> Maven Project
** selezionare "Create a simple project (skip archetype selection)
** "Group id:" -> "tutorial.jdbc"
** "Artifact id:" -> "jdbc-training"
** lasciare vuoti gli altri parametri

== Configurazione dipendenze

[%step]
* Aprire il pom.xml
* Andare nella scheda *Depencencies*
** Selezionare *Add...*
** cercare h2database
** selezionare la versione 1.4.191 [jar]
** salvare e verificare la presenza del jar selezionato in *Maven Dependencies*

== Creazione classe per connessione al db

[%step]
* creare un package *training.jdbc* dentro source folder *src/main/java*
** tasto destro sul source folder *src/main/java* -> *new*
** cercare package
** inserire come nome *training.jdbc*
* creare la classe *DBConfig* nel package precedentemente creato
** file -> new -> other e cercare Class

== Parametri e connessione DB

[[app-listing]]
[source,java]
.DBConfig.java
----
import java.sql.*
public class DBConfig {

  public final static String DB_URL = "jdbc:h2:~/corsojava";
  public final static String DB_USER = "sa";
  public final static String DB_PASSWORD = "";

  public static Connection getConnection() throws SQLException {
    return DriverManager.getConnection(
        DBConfig.DB_URL, DBConfig.DB_USER, DBConfig.DB_PASSWORD);
  }

}
----

== Creazione tabella Person
* scrivere una classe con main che crei un tabella employees (id,
name, surname)
[source,sql]
----
CREATE TABLE employees (
 id SERIAL NOT NULL PRIMARY KEY,
 name VARCHAR(255), surname VARCHAR(255)
)
----

== Creazione tabella Person^(2)^
[[app-listing]]
[source,java]
.DBCreator.java
----
import java.sql.*
public class DBCreator {
  private final static String CREATE_DB_DDL =
      "CREATE TABLE employees ("
          + "id SERIAL NOT NULL PRIMARY KEY,"
          + "name VARCHAR(255), surname VARCHAR(255))";

  public static void main(String[] args) throws SQLException {
    try (Connection con = DBConfig.getConnection()) {
      try (Statement stmt = con.createStatement()) {
        //Esegue la query
        stmt.executeUpdate(CREATE_DB_DDL);
      }
    }
  }
}
----

== Definizione Bean Employee
* Definire una classe Employee
** che contenga un campo id, name e surnme
** un metodo toString che stampi "nome cognome (id='id')"
** inserirla nel package *training.jdbc*

== Definizione Bean Employee^(2)^
[[app-listing]]
[source,java]
.Employee.java
----
import lombok.Data;
import lombok.Builder;
@Data @Builder
public class Employee {

  private Integer id;
  private String name;
  private String surname;

  @Override
  public String toString() {
    return String.format("%s %s (id=%d)", surname, name, id);
  }
}
----
* Lombok (http://projectlombok.org)
* @Data aggiunge getter,setter,equals,hashcode,..
* @Builder aggiunge metodi del pattern *Builder*

== Utilizzo @Builder
[source,java]
----
import lombok.Builder;
@Builder
public class Employee {
//..
}
----
----
Employee.builder()
  .id(rs.getInt("id"))
  .name(rs.getString("name"))
  .surname(rs.getString("surname"))
  .build());
----
== Definizione EmployeeDao
* Definire una classe EmployeeDao
** che contenga un metodo per estrarre la lista di ogetti `Employee`
** che utilizzi il metodo `DBConfig.getConnection()`
[source,java]
----
private final static String SELECT_EMPLOYEES =
  "SELECT * FROM employees ORDER BY surname, name";
//...
public List<Employee> list() throws SQLException;
//..
}
----

== Definizione EmployeeDao^(2)^
[[app-listing]]
[source,java]
.EmployeeDao.java
  private final static String SELECT_EMPLOYEE = "SELECT * FROM employees WHERE id = ?";
  public List<Employee> list() throws SQLException {
    try(Connection con = DBConfig.getConnection()) {
      PreparedStatement ps;
      if (limit.isPresent()) {
        ps = con.prepareStatement(SELECT_EMPLOYEES);
        ps.setInt(1, limit.get());
      } else {
        ps = con.prepareStatement(SELECT_EMPLOYEES);
      }
      List<Employee> employees = new ArrayList<>();
      try (ResultSet rs = ps.executeQuery()) {
        while(rs.next()) {
          employees.add(
              Employee.builder()
              .id(rs.getInt("id"))
              .name(rs.getString("name"))
              .surname(rs.getString("surname"))
              .build());
        }
        return employees;
      }
    }
  }

== Interfaccia CommandLine
* definire una classe `CommandLine`
* con un metodo main che utilizzi EmployeeDao per stampare la lista degli Employee
* provare ad inserire in h2 una riga nella tabella employees
* utilizzare la classe CommandLine per visualizzare la lista degli Employee

== Interfaccia CommandLine^(2)^
[[app-listing]]
[source,java]
.CommandLine.java
----
public class CommandLine {
  private final EmployeeDao employeeDao;

  public CommandLine() {
    employeeDao = new EmployeeDao();
  }

  public void elencoDipendenti() throws SQLException {
    for(Employee emp : employeeDao.list(Optional.empty())) {
      System.out.println(emp);
    }
    System.out.println("\n");
  }
//..
}
----

== Inserimento tramite Dao
* nell'*EmployeeDao* definire un metodo
[source,java]
----
public boolean persist(String name, String surname) throws SQLException;o
----

== Inserimento tramite Dao^(2)^
[[app-listing]]
[source,java]
.EmployeeDao.java
----
  private final static String INSERT_EMPLOYEE = "INSERT INTO employees (name, surname) values (?, ?)";
  public boolean persist(String name, String surname) throws SQLException {
    try(Connection con = DBConfig.getConnection()) {
      try(PreparedStatement ps =
          con.prepareStatement(INSERT_EMPLOYEE)) {
        ps.setString(1, name);
        ps.setString(2, surname);
        return ps.execute();
      }
    }
----

== CommandLine: creazione menu

[[app-listing]]
[source,java]
.CommandLine.java
----
  private void menu() {
    System.out.println("= Anagrafica Dipendenti =");
    System.out.println("== Menu Principale ==\n");
    System.out.println("1) Elenco dipendenti");
    System.out.println("2) Inserisci dipendente");
    System.out.println("3) Modifica dipendente");
    System.out.println("4) Elimina dipendente\n");

    System.out.println("0) Termina applicazione\n\n");
    System.out.println("Seleziona una operazione\n");
  }
----

== CommandLine: Scanneer
[[app-listing]]
[source,java]
.CommandLine.java
----
import java.util.Scanner;
//..
  private final Scanner scanner;
  private final EmployeeDao employeeDao;

  public CommandLine(Scanner scanner) {
    this.scanner = scanner;
    employeeDao = new EmployeeDao();
  }
----

== CommandLine: Scanneer^(2)^
[[app-listing]]
[source,java]
.CommandLine.java
----
  public void main() throws SQLException {
    String command = scanner.next();
      switch (command) {
        case "0":
          System.out.println("Anagrafica terminata");
          return;
        case "1":
          elencoDipendenti();
          break;
        case "2":
          inserisciDipendente();
          break;
        default:
          System.out.println(String.format("Operazione %s non riconosciuta", command));
      }
      System.out.println("Seleziona un'operazione (da 0 a 4)\n");
      main();
  }
----

Create due metodi vuoti  *elencoDipendenti()* ed *inserisciDipendente()*


== elencoDipendenti()

[[app-listing]]
[source,java]
.CommandLine.java
----
public void elencoDipendenti() throws SQLException;
----

Implementare un metodo elencoDipendenti stampi la lista dei dipendenti sullo standard output

== elencoDipendenti()^(2)^

[[app-listing]]
[source,java]
.CommandLine.java
----
  public void elencoDipendenti() throws SQLException {
    for(Employee emp : employeeDao.list(Optional.empty())) {
      System.out.println(emp);
    }
    System.out.println("\n");
  }
----

== inserisciDipendente()

* scrivere un metodo inserisciDipendente()
* che utilizzi il Dao..
* che utilizzi System::out e Scanner::next per leggere nome e cognome
[source,java]
----
System.out.print("Inserisci il cognome: ");
String surname = scanner.next();
----

== inserisciDipendente()^(2)^
[[app-listing]]
[source,java]
.CommandLine.java
----
  public void inserisciDipendente() throws SQLException {

    System.out.println("== Inserimento di una persona nel db ==");

    System.out.print("Inserisci il cognome: ");
    // get their input as a String
    String surname = scanner.next();

    System.out.print("Inserisci il nome: ");
    // get their input as a String
    String name = scanner.next();

    employeeDao.persist(name, surname);

    System.out.println(String.format("%s %s inserito in anagrafica\n", surname, name));
  }
----

== CommandLine: mettere tutto insieme
[[app-listing]]
[source,java]
.CommandLine.java
----
//...
  public void start() throws SQLException {
    menu();
    main();
  }

  public static void main(String[] args) throws SQLException {
    // create a scanner so we can read the command-line input
    try (Scanner scanner = new Scanner(System.in)) {
      CommandLine cl = new CommandLine(scanner);
      cl.start();
    }
  }
----

== Conquer the CRUD

* CRUD -> Create, Read, Update, Delete
* implementare nel EmployeeDao ed in CommandLine i metodi per la modifica e cancellazione

*That's all folk!*

